#!/usr/bin/env bash
set -euo pipefail

TARGET="${1:?usage: rental_run_selfplay_train.sh <user@host> <game>}"
GAME="${2:?usage: rental_run_selfplay_train.sh <user@host> <game>}"
KEY_PATH="${AFFINE_RENTAL_KEY_PATH:-${HOME}/.ssh/affine_rental}"
REMOTE_DIR="${AFFINE_REMOTE_DIR:-/root/affine-swarm}"
REMOTE_PYTHON="${AFFINE_REMOTE_PYTHON:-${REMOTE_DIR}/.venv/bin/python}"
LOG_PATH="${AFFINE_REMOTE_LOG_PATH:-/root/logs/${GAME}_selfplay_train.log}"

SELFPLAY_EPISODES="${AFFINE_GAME_SELFPLAY_EPISODES:-128}"
SELFPLAY_SIMULATIONS="${AFFINE_GAME_SELFPLAY_SIMULATIONS:-64}"
SELFPLAY_EPOCHS="${AFFINE_GAME_POLICY_EPOCHS:-5}"
SELFPLAY_BATCH_SIZE="${AFFINE_GAME_POLICY_BATCH_SIZE:-1024}"
SELFPLAY_DEVICE="${AFFINE_GAME_POLICY_DEVICE:-}"
SELFPLAY_QUICK_GAMES="${AFFINE_GAME_SELFPLAY_QUICK_GAMES:-50}"
SELFPLAY_TEACHER_GAMES="${AFFINE_GAME_SELFPLAY_TEACHER_GAMES:-200}"
SELFPLAY_QUICK_MIN_WIN_RATE="${AFFINE_GAME_SELFPLAY_QUICK_MIN_WIN_RATE:-0.55}"
SELFPLAY_TEACHER_MIN_WIN_RATE="${AFFINE_GAME_SELFPLAY_TEACHER_MIN_WIN_RATE:-0.90}"
SELFPLAY_REQUIRED_STREAK="${AFFINE_GAME_SELFPLAY_REQUIRED_STREAK:-2}"
SELFPLAY_MAX_ROUNDS="${AFFINE_GAME_SELFPLAY_MAX_ROUNDS:-200}"
SELFPLAY_QUICK_INTERVAL="${AFFINE_GAME_SELFPLAY_QUICK_INTERVAL:-1}"
SELFPLAY_TEACHER_INTERVAL="${AFFINE_GAME_SELFPLAY_TEACHER_INTERVAL:-1}"
SELFPLAY_SYNC_INTERVAL="${AFFINE_GAME_SELFPLAY_SYNC_INTERVAL:-10}"
SELFPLAY_AUTOTUNE_BATCH="${AFFINE_GAME_SELFPLAY_AUTOTUNE_BATCH:-0}"
SELFPLAY_LONGRUN="${AFFINE_GAME_SELFPLAY_LONGRUN:-0}"
SELFPLAY_REPO="${AFFINE_GAME_POLICY_REPO:-}"
HF_TOKEN_VALUE="${HF_TOKEN:-}"

REMOTE_SCRIPT="scripts/game/targon_game_smoke.py"
if [ "${SELFPLAY_LONGRUN}" = "1" ]; then
  REMOTE_SCRIPT="scripts/game/targon_game_selfplay_longrun.py"
fi

ssh -i "${KEY_PATH}" -o StrictHostKeyChecking=no "${TARGET}" "\
  cd '${REMOTE_DIR}' && \
  export AFFINE_GAME_NAME='${GAME}' && \
  export AFFINE_GAME_SELFPLAY_TRAIN=1 && \
  export AFFINE_GAME_SELFPLAY_EPISODES='${SELFPLAY_EPISODES}' && \
  export AFFINE_GAME_SELFPLAY_SIMULATIONS='${SELFPLAY_SIMULATIONS}' && \
  export AFFINE_GAME_POLICY_EPOCHS='${SELFPLAY_EPOCHS}' && \
  export AFFINE_GAME_POLICY_BATCH_SIZE='${SELFPLAY_BATCH_SIZE}' && \
  export AFFINE_GAME_POLICY_DEVICE='${SELFPLAY_DEVICE}' && \
  export AFFINE_GAME_SELFPLAY_QUICK_GAMES='${SELFPLAY_QUICK_GAMES}' && \
  export AFFINE_GAME_SELFPLAY_QUICK_MIN_WIN_RATE='${SELFPLAY_QUICK_MIN_WIN_RATE}' && \
  export AFFINE_GAME_SELFPLAY_TEACHER_GAMES='${SELFPLAY_TEACHER_GAMES}' && \
  export AFFINE_GAME_SELFPLAY_TEACHER_MIN_WIN_RATE='${SELFPLAY_TEACHER_MIN_WIN_RATE}' && \
  export AFFINE_GAME_SELFPLAY_REQUIRED_STREAK='${SELFPLAY_REQUIRED_STREAK}' && \
  export AFFINE_GAME_SELFPLAY_MAX_ROUNDS='${SELFPLAY_MAX_ROUNDS}' && \
  export AFFINE_GAME_SELFPLAY_QUICK_INTERVAL='${SELFPLAY_QUICK_INTERVAL}' && \
  export AFFINE_GAME_SELFPLAY_TEACHER_INTERVAL='${SELFPLAY_TEACHER_INTERVAL}' && \
  export AFFINE_GAME_SELFPLAY_SYNC_INTERVAL='${SELFPLAY_SYNC_INTERVAL}' && \
  export AFFINE_GAME_SELFPLAY_AUTOTUNE_BATCH='${SELFPLAY_AUTOTUNE_BATCH}' && \
  export AFFINE_GAME_POLICY_REPO='${SELFPLAY_REPO}' && \
  export HF_TOKEN='${HF_TOKEN_VALUE}' && \
  PYTHONPATH='${REMOTE_DIR}' '${REMOTE_PYTHON}' '${REMOTE_SCRIPT}' \
  > '${LOG_PATH}' 2>&1"

echo "LOG ${LOG_PATH}"
